language: node_js
env:
  - DATABASE_URL = 'postgresql://codex:pg123@localhost:5432/greetings'
node_js:
  - 12
before_script:
  - 
  - psql -c 'create database greetings;' -U codex
  - psql -U codex -d greetings -a -f database.sql
services:
  - postgresql
addons:
  postgresql: '9.4'
  apt:
    packages:
      - postgresql-server-dev-9.4