language: node_js
env:
  - DATABASE_URL = 'postgresql://localhost:5432/greetings_tests'
node_js:
  - 12
before_script:
  - psql -c 'create database greetings_tests;' -U codex
  - psql -U codex -d greetings_tests -a -f database.sql
services:
  - postgresql
addons:
  postgresql: '9.4'
  apt:
    packages:
      - postgresql-server-dev-9.4